version: 2
jobs:
  php:
    working_directory: ~/signer
    docker:
    - image: circleci/php:7
    steps:
    - checkout:
        path: ~/signer
    - run: composer install
    - run: php ./php/tests/signer_test.php
  node:
    working_directory: ~/signer/node
    docker:
    - image: circleci/node:8
    steps:
    - checkout:
        path: ~/signer
    - run: npm install
    - run: ./node_modules/.bin/mocha
  node-hebe:
    working_directory: ~/signer-hebe/hebe-node
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/signer-hebe
      - run: npm install
      - run: ./node_modules/.bin/mocha
  jvm:
    working_directory: ~/signer
    docker:
    - image: circleci/openjdk:8
    steps:
    - checkout:
        path: ~/signer
    - run: ./gradlew :jvm:check jacocoTestReport
    - store_test_results:
        path: ./build/test-results
  jvm-hebe:
    working_directory: ~/signer
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout:
          path: ~/signer
      - run: ./gradlew :hebe-jvm:check jacocoTestReport
      - store_test_results:
          path: ./build/test-results
  python:
    working_directory: ~/signer/python
    docker:
    - image: circleci/python:3.6
    steps:
    - checkout:
        path: ~/signer
    - run: pip install --user .[testing]
    - run: python -m pytest .

workflows:
  version: 2
  test:
    jobs:
    - php
    - node
    - node-hebe
    - jvm
    - jvm-hebe
    - python
